name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'


      - name: Install dependencies
        run: |
          # Rscript -e
          # remotes package
          Rscript -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")'
          # Install Package dependencies
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
          # golem::document_and_reload()
          Rscript -e 'install.packages("roxygen2", repos = "https://cloud.r-project.org/")'
          # devtools::check()
          Rscript -e 'install.packages("devtools", repos = "https://cloud.r-project.org/")'

      - name: R CMD check
        run: |
          # Rscript -e
          Rscript -e 'golem::document_and_reload()'
          # R CMD check
          Rscript -e 'devtools::check()'
