# .github/workflows/ci.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: CI Pipeline

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
          use-public-rspm: true # This helps with faster and more reliable package installation

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes", repos = "https://cloud.r-project.org")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Runs tests
        run: Rscript -e 'devtools::test()'

      - name: R CMD check
        run: |
          Rscript -e 'golem::document_and_reload()'
          Rscript -e 'devtools::check()'
