on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      # dependencies များကို install လုပ်ခြင်း
      - name: Install dependencies
        run: |
          # Rscript -e ကိုအသုံးပြုပြီး R code ကို run ပါ။
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      # R CMD check ကို run ခြင်း
      - name: R CMD check
        run: |
          # Rscript -e ကိုအသုံးပြုပြီး R code ကို run ပါ။
          Rscript -e 'golem::document_and_reload()'
          Rscript -e 'devtools::check()'
